# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy Project to Surge

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:12
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
      name :setup node
      uses: actions/setup-node@v2
      with:
        node-version: 12
    # Step to Install Surge
    - name: Installing Surge
      run: npm install --global surge

    # Deploy App to Surge
    - name: Deploying Project to Surge
      run: surge ./ expense-trackesr.sh --token ${{ secrets.SURGE_TOKEN }}
